### ISSUE TITLE
a question about running 

### ISSUE THREAD

**Issue by xinobu** [dhh1995/SCL#2]
Thanks for your great work!
Here is a question when I tried to run the 'single task trainning' part.
After finishing 'prepare dataset' part, I copy the code to run main.py, but it raised an error like that:

Traceback (most recent call last):
  File "main.py", line 32, in <module>
    from jactorch.cli import dump_metainfo
  File "/media/icrn-20201009-cnum1/jiangguanyu/Jacinle/jactorch/__init__.py", line 14, in <module>
    from .functional import *
  File "/media/icrn-20201009-cnum1/jiangguanyu/Jacinle/jactorch/functional/__init__.py", line 20, in <module>
    from .quantization import *
  File "/media/icrn-20201009-cnum1/jiangguanyu/Jacinle/jactorch/functional/quantization.py", line 42, in <module>
    quantize = Quantize.apply
AttributeError: type object 'Quantize' has no attribute 'apply

I don't know what's wrong with it and really need somebody's help.

**Comment by dhh1995** [comment]
Thanks for your interest in our work.
Please try the [c9fcbb5](https://github.com/vacancy/Jacinle/tree/c9fcbb55c73679ff17488f10b71b574a2ca044d2) version of the third party repo Jacinle (which is mentioned in the README).
