### ISSUE TITLE
question:How could I solve this problem?

### ISSUE THREAD

**Issue by zetaodu** [dhh1995/SCL#3]
➜  SCL git:(master) ✗ jac-run main.py -d ~/data/RAVEN-10000 -t center_single --use-gpu -v \
-lr 0.005 -vlr 0.005 -wd 0.01 -tsd 80 -fg 10 -nf 80 \
-chd 16 16 32 32 -rb -erb -vhd 128 -hd 64 32 -lhd 128
10 14:02:35 Loading jacinle config: /home/featurize/Jacinle/jacinle.yml.
10 14:02:35 Loading vendor: ReservoirSample-PyTorch.
10 14:02:35 Loading vendor: AdvancedIndexing-PyTorch.
10 14:02:35 Loading vendor: SynchronizedBatchNorm-PyTorch.
10 14:02:35 Loading vendor: PreciseRoIPooling-PyTorch.
10 14:02:35 Loading vendor: SceneGraphParser.
10 14:02:35 Loading vendor: JacMLDash.
10 14:02:35 Loading vendor: PyGCO.
10 14:02:35 Loading vendor: PyPatchMatch.
dumps/ce_lr0005_nf80_bs128_edNone_ne5_vlr0.005_hd64_32_is160_160_fg10_tsd80_chd16_16_32_32_vhd128_lhd128_rg2_res_wd001
10 14:02:38 Writing metainfo to file: "dumps/ce_lr0005_nf80_bs128_edNone_ne5_vlr0.005_hd64_32_is160_160_fg10_tsd80_chd16_16_32_32_vhd128_lhd128_rg2_res_wd001/meta.json".
  0%|                                                                                                                                                                               | 0/47 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 587, in <module>
    main()
  File "main.py", line 579, in main
    trainer.train_eval(train_data, val_data)
  File "/home/featurize/SCL/analogy/train/trainer.py", line 327, in train_eval
    train_meters = self.train_epoch(train_loader)
  File "/home/featurize/SCL/analogy/train/trainer.py", line 230, in train_epoch
    loss, monitors, output_dict, extras = self.step(data)
  File "/home/featurize/Jacinle/jactorch/train/env.py", line 135, in step
    loss, monitors, output_dict = self._model(feed_dict)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/featurize/Jacinle/jactorch/parallel/data_parallel.py", line 66, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/featurize/SCL/analogy/nn/model.py", line 220, in forward
    pred_symbol = self.v2s(visual)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/featurize/SCL/analogy/nn/visual_model.py", line 102, in forward
    x = self.cnn(x)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/featurize/SCL/analogy/nn/modules/modules.py", line 205, in forward
    x = conv_block(x)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/featurize/SCL/analogy/nn/modules/modules.py", line 146, in forward
    _ = conv(_)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/featurize/Jacinle/jactorch/nn/cnn/conv.py", line 79, in forward
    return self._forward_conv(*self._forward_padding(input))
  File "/home/featurize/Jacinle/jactorch/nn/cnn/conv.py", line 85, in _forward_conv
    return self.conv(padded, **kwargs)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    return F.conv2d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode),
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/torch/nn/functional.py", line 3576, in _pad
    raise NotImplementedError
NotImplementedError
➜  SCL git:(master) ✗ jac-run main.py -d ~/data/RAVEN-10000 -t center_single --use-gpu -v  
10 14:04:51 Loading jacinle config: /home/featurize/Jacinle/jacinle.yml.
10 14:04:51 Loading vendor: ReservoirSample-PyTorch.
10 14:04:51 Loading vendor: AdvancedIndexing-PyTorch.
10 14:04:51 Loading vendor: SynchronizedBatchNorm-PyTorch.
10 14:04:51 Loading vendor: PreciseRoIPooling-PyTorch.
10 14:04:51 Loading vendor: SceneGraphParser.
10 14:04:51 Loading vendor: JacMLDash.
10 14:04:51 Loading vendor: PyGCO.
10 14:04:51 Loading vendor: PyPatchMatch.
dumps/ce_lr0005_nf4_bs128_edNone_ne5_hd32_16_is160_160_chd8_16_32_32_rg2
10 14:04:54 Writing metainfo to file: "dumps/ce_lr0005_nf4_bs128_edNone_ne5_hd32_16_is160_160_chd8_16_32_32_rg2/meta.json".
  0%|                                                                                                                                                                               | 0/47 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 587, in <module>
    main()
  File "main.py", line 579, in main
    trainer.train_eval(train_data, val_data)
  File "/home/featurize/SCL/analogy/train/trainer.py", line 327, in train_eval
    train_meters = self.train_epoch(train_loader)
  File "/home/featurize/SCL/analogy/train/trainer.py", line 230, in train_epoch
    loss, monitors, output_dict, extras = self.step(data)
  File "/home/featurize/Jacinle/jactorch/train/env.py", line 135, in step
    loss, monitors, output_dict = self._model(feed_dict)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/featurize/Jacinle/jactorch/parallel/data_parallel.py", line 66, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/featurize/SCL/analogy/nn/model.py", line 220, in forward
    pred_symbol = self.v2s(visual)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/featurize/SCL/analogy/nn/visual_model.py", line 102, in forward
    x = self.cnn(x)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/featurize/SCL/analogy/nn/modules/modules.py", line 205, in forward
    x = conv_block(x)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/featurize/SCL/analogy/nn/modules/modules.py", line 146, in forward
    _ = conv(_)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/featurize/Jacinle/jactorch/nn/cnn/conv.py", line 79, in forward
    return self._forward_conv(*self._forward_padding(input))
  File "/home/featurize/Jacinle/jactorch/nn/cnn/conv.py", line 85, in _forward_conv
    return self.conv(padded, **kwargs)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    return F.conv2d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode),
  File "/environment/python/versions/3.7.4/lib/python3.7/site-packages/torch/nn/functional.py", line 3576, in _pad
    raise NotImplementedError
NotImplementedError

**Comment by dhh1995** [comment]
Please check the Jacinle version you used. We use the version [c9fcbb5](https://github.com/vacancy/Jacinle/tree/c9fcbb55c73679ff17488f10b71b574a2ca044d2).

**Comment by zetaodu** [comment]
I do use the version c9fcbb5

**Comment by zetaodu** [comment]
oh,I see!!!thanks.
